### ISSUE TITLE
GetValue requires defaultValue argument

### ISSUE THREAD

**Issue by restouffer** [robotpy/pyntcore#22]
Since the fix for #20, it appears that there is a new required defaultValue argument to NetworkTables.getValue. Calling it without a second argument results in:
```
TypeError: getValue(): incompatible function arguments. The following argument types are supported:
    1. (self: _pyntcore._ntcore.NetworkTable, key: str, value: object) -> object
```

This does not match previous behavior or the [C++ call](https://first.wpi.edu/FRC/roborio/release/docs/cpp/classnt_1_1NetworkTable.html#a41504ace23cb0ef5f70ec4dd8bd2c11a). Was that change intentional? Would it be possible for that function to return None if no default is given and no value is found in the network table for the given key?

**Comment by auscompgeek** [comment]
This matches the documented behaviour: https://robotpy.readthedocs.io/projects/pynetworktables/en/latest/api.html#networktables.NetworkTable.getValue

**Comment by virtuald** [comment]
Yes, the change was intentional, in that it is supposed to match pynetworktable's implementation, not necessarily the C++ implementation.

**Comment by virtuald** [comment]
Also, all the other getXXX functions require a default value to be specified, why not this one too?

**Comment by virtuald** [comment]
Furthermore, the C++ call returns an nt::Value, whereas pynetworktables (and this fix) returns the contents of the value.
