### ISSUE TITLE
NetworkTableEntry.setValue should take the inner types

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/pyntcore#9]
Probably the best way to fix this is for pybind11 to auto-cast bool/int/float/str/bytes to nt::Value, so that we fix this across the board. Bonus points for auto-converting sequences.

(This is currently breaking magicbot.tunable and magicbot.feedback.)

See also: #2

**Comment by virtuald** [comment]
Could create a type caster maybe?

**Comment by auscompgeek** [comment]
That's what I was thinking.

**Comment by auscompgeek** [comment]
Hmm... how would you implement a type caster without any special handling for cast?

**Comment by virtuald** [comment]
Might be easier to just have a function that does the right thing, and add lambdas that call that function (a la https://github.com/robotpy/pyntcore/blob/master/_pyntcore/src/py2value.cpp utility functions)
